<a href="https://colab.research.google.com/github/wheelstop/2025D.M/blob/main/5_%EA%B4%80%EA%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 이항 관계 예제

In [ ]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

In [ ]:
A = {1, 2, 3}
B = {2, 3, 4}
#A에서 B로 가는 이항 관계 R
R = {(1, 2), (2, 3), (3, 2), (3, 4)}

print("관계: R", R)

관계: R {(2, 3), (3, 2), (1, 2), (3, 4)}


# 관계 행렬 표현

In [ ]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

In [ ]:
A_list = sorted(A)
B_list = sorted(B)

relation_matrix = np.zeros((len(A_list), len(B_list)), dtype=int)

for i, a in enumerate(A_list): #a 가 1일 때 보고
  for j, b in enumerate(B_list): # b 가 1일 때도 보고
    if (a, b) in R: # 1, 2 가 관계 R 에 있었습니까?
      relation_matrix[i, j] = 1 #a, b가 해당하면 모두 1로 만들래!
print("관계 행렬 (rows: A, columns: B):")
print(relation_matrix)

관계 행렬 (rows: A, columns: B):
[[1 0 0]
 [0 1 0]
 [1 0 1]]


A: 1, 2, 3

B: 2, 3, 4

# 합성 관계 예제

In [ ]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

In [ ]:
# R: A -> B
# S: B ->C
C = {'x', 'y'}
S = {(2, 'x'), (3, 'y'), (4, 'x')}

# 합성 관계 R * S
composed_relation = set()

for (a, b1) in R:
  for (b2, c) in S:
    if b1 == b2:
      composed_relation.add((a, c))

print("\n합성관계 R * S: ", composed_relation)


합성관계 R * S:  {(3, 'x'), (2, 'y'), (1, 'x')}


R의 치역이 S의 공역과 동일해야함